### ISSUE TITLE
call to undefined function guzzlehttp\psr7\build_query()

### ISSUE THREAD

**Issue by juanfelipepipen** [maxhelias/php-nominatim#19]
## Guzzle ^ 7.3 incompatibility

The library is not compatible with ^ 7.3 since the guzzlehttp\psr7\build_query () method has been deprecated

### Solution found

In the Nominatim file on line 189 it is required to replace all calls to guzzlehttp\psr7\build_query() by http_build_query

// Old 
$query = \GuzzleHttp\Psr7\build_query($nRequest->getQuery(), PHP_QUERY_RFC1738);

// New
$query = http_build_query($nRequest->getQuery());`

**Comment by maxhelias** [comment]
Thanks ! This is fixed on the new release : https://github.com/maxhelias/php-nominatim/releases/tag/2.3.0
