### ISSUE TITLE
Invalid class names in phpdoc blocks

### ISSUE THREAD

**Issue by xemlock** [maxhelias/php-nominatim#4]
## Bug, feature or question?

_Is this a bug, a feature request or a question?_

Bug.

_Give us a short description._

Class names present in `@param` and `@return` fields inside phpdoc blocks are missing prefixing slash, which makes them relative to the namespace (according to the [phpdocumentor rules](http://docs.phpdoc.org/guides/types.html#types-of-types)). In result they are invalid and break auto-completion in IDEs.

### Version and provider

_What version of PHP-Nominatim does this relates to?_

Any.

_Is this an issue with a provider? If yes, which one? (Search, Reverse, Lookup)_

All.

### Reproduction

_How can we replicate this issue?_

The bug already manifested itself in the documentation. Look at class names auto-generated by phpdoc -  there are obviously invalid ones like `\maxh\Nominatim\Guzzle\Client` ([here](https://github.com/maxhelias/php-nominatim/blob/be9393be8/docs/classes/maxh.Nominatim.Nominatim.html#L473)).

You can also see it in IDEs - class names are resolved to non-existent ones:

![phpstorm-nominatim](https://user-images.githubusercontent.com/952555/34906604-03493918-f871-11e7-9ac3-1c4c9fdfa131.png)

**Comment by maxhelias** [comment]
I merge your pull request, thanks again 👍

**Comment by xemlock** [comment]
You're welcome! Any rough timeframe for a release? 🙂

**Comment by maxhelias** [comment]
Yes, I can do this to you at the beginning of the week :)

**Comment by maxhelias** [comment]
Version 1.2.3 is now available ;)
