### ISSUE TITLE
Naming of countrycodes parameter is wrong

### ISSUE THREAD

**Issue by straschek-io** [maxhelias/php-nominatim#7]
## Bug

The parameter passed to nominatim for limiting the search scope to a country in https://github.com/maxhelias/php-nominatim/blob/master/src/Search.php#L164 is wrong.

It should be named `countrycodes`, not `countrycode`.

### Version and provider

Current master, search provider

### Reproduction

Compare:
https://nominatim.openstreetmap.org/search?format=json&q=41460&limit=1&countrycode=de 
(leads to same result as https://nominatim.openstreetmap.org/search?format=json&q=41460&limit=1&countrycodes=se)
vs.
https://nominatim.openstreetmap.org/search?format=json&q=41460&limit=1&countrycodes=de

**Comment by maxhelias** [comment]
Thank you for your contribution 👍
