### ISSUE TITLE
about updating nominatim...

### ISSUE THREAD

**Issue by mbutler-79** [maxhelias/php-nominatim#9]
## Bug, feature or question?

Is this a bug, a feature request or a question?

Give us a short description.

### Version and provider

What version of PHP-Nominatim does this relates to?

Is this an issue with a provider? If yes, which one? (Search, Reverse, Lookup)

### Reproduction

How can we replicate this issue?

**Comment by mbutler-79** [comment]
question

**Comment by mbutler-79** [comment]
Hi,
I wanted to know how can I update nominatim without setting this line in settings/local.php :

@define('CONST_Replication_Url', 'https://planet.openstreetmap.org/replication/minute');

I mean I don't want to sync with osm, I want to update nominatim whenever I would like.
for example I have a osm data for two months ago, now I want to update them. but I don't know if I set replicarion service with above value, all data are updated from two months ago until now ?
how can I sure that updating process is correct ?

better to use this address ?
http://download.geofabrik.de/europe-updates/

Thanks in Advance

**Comment by maxhelias** [comment]
Sorry, i don't have the answer to your question.
This is more of the order of the application itself and has nothing to do with this project, I invite you to ask your question here : https://github.com/openstreetmap/Nominatim

Or take a look at the wiki, like this article : 
https://wiki.openstreetmap.org/wiki/Osmupdate

**Comment by mbutler-79** [comment]
Ok, thanks maxhelias
